/* eslint-disable react-hooks/exhaustive-deps */
import React, { useContext } from "react";
import { TickersAreaContainer } from "./style";
import { DataContext } from "contexts/DataContextContainer";
import {
    Logo,
    IconEyes,
} from "assets/images";
import { Button, Image } from "react-bootstrap";
import { show_digit_number } from "service/utils";
import { useHistory } from "react-router-dom";

function TickersArea() {
    const history = useHistory();
    const {
        totalViewCt, totalKoiCt
    } = useContext(DataContext);

    const onClickGetKOI = () => {
        history.push('/faucet');
    }
    return (
        <TickersAreaContainer>
            <div className="ticker-area">
                <div className="koi-area d-flex flex-row">
                    <div className="d-flex flex-row flex1">
                        <div className="w50">
                            <Image src={IconEyes} width="35" />
                        </div>
                        <div className="flex1 flex-column">
                            <div className="font-balance1">
                                {show_digit_number(totalViewCt)}
                            </div>
                            <div className="font-cap1">
                                views
                            </div>
                        </div>
                    </div>
                    <div className="d-flex flex-row flex1">
                        <div className="w50">
                            <Image src={Logo} width="43" />
                        </div>
                        <div className="flex1 flex-column">
                            <div className="font-balance1">
                                {show_digit_number(totalKoiCt)}
                            </div>
                            <div className="font-cap1">
                                KOI earned
                            </div>
                        </div>
                    </div>
                </div>
                <hr className="line4"></hr>
                <div className="ticker-body">
                    <div className="font-18-40"><b>Koi</b> (noun)</div>
                    <div className="font-15-17">\ ˈkȯi  \</div>
                    <div className="d-flex flex-row mt-20">
                        <div className="w20"><span>1</span></div>
                        <div className="font-cap2 flex1">A network of peers dedicated to a better internet</div>
                    </div>
                    <div className="d-flex flex-row mt-20">
                        <div className="w20"><span>2</span></div>
                        <div className="font-cap2 flex1">A token (KOI) that can only be generated by attention, and serves as a unit of exchange within the network. 1,000 tokens are distributed each day</div>
                    </div>
                    <div className="d-flex flex-row mt-20">
                        <div className="w20"><span>3</span></div>
                        <div className="font-cap2 flex1">a carp (Cyprinus carpio) bred especially in Japan for large size and a variety of colors and often stocked in ornamental ponds</div>
                    </div>
                </div>
            </div>
            <div className="ticker-area">
                <div className="font-balance1 ml-10">
                    The rules
                </div>
                <hr className="line4"></hr>
                <div className="ticker-body">
                    <div className="d-flex flex-row mt-20">
                        <div className="w20"><span>1</span></div>
                        <div className="font-cap2 flex1">Anything posted on Koi is permanent. You cannot remove it. We cannot remove it.</div>
                    </div>
                    <div className="d-flex flex-row mt-20">
                        <div className="w20"><span>2</span></div>
                        <div className="font-cap2 flex1">If you don’t own it, don’t post it.</div>
                    </div>
                    <div className="d-flex flex-row mt-20">
                        <div className="w20"><span>3</span></div>
                        <div className="font-cap2 flex1">Keep it positive. Your reputation is on the line.</div>
                    </div>
                    <div className="d-flex flex-row mt-20">
                        <div className="w20"><span>4</span></div>
                        <div className="font-cap2 flex1">Koi is dedicated to fostering an ecosystem of creators where everyone is welcome. Do not post anything that degrades our fellow humans.</div>
                    </div>
                    <div className="mt-30 font-cap3">If you see something that violates these rules, please let us know at <a href="mailto:hello@openkoi.com">hello@openkoi.com</a>.</div>
                </div>
            </div>
            <div className="ticker-area">
                <div className="font-balance1 ml-10">
                    Need KOI?
                </div>
                <hr className="line4"></hr>
                <div className="ticker-body">
                    <div className="d-flex flex-row mt-20">
                        <div className="font-cap2 flex1">Get some free KOI from the KOI Faucet.</div>
                    </div>
                    <div className="d-flex flex-row mt-20 justify-content-center">
                        <Button className="btn-outline pl-15 pr-15" onClick={onClickGetKOI}>
                            Get KOI
                        </Button>
                    </div>
                </div>
            </div>
        </TickersAreaContainer>
    );
}

export default TickersArea;
